### ISSUE TITLE
Invalid copy constructor selected in some cases

### ISSUE THREAD

**Issue by ukreator** [mapbox/variant#122] opened 2016-10-05 10:53 UTC
Simple code snippet to reproduce the issue:

```c++
struct X
{
    template <typename ValueType>
    X(const ValueType&)  {}
};

int main()
{
    mapbox::util::variant<X, int> a{123}; // init with int
    decltype(a) b = a;
    assert(a.which() == b.which());
}
```

boost::variant works fine in this case. This issue was originally spotted by random failures after replacing boost::variant with map box::variant. One of the types in the list was boost::any which has a templated constructor like in struct X above.

**Comment by lightmare** [comment] 2016-10-05 12:10
This is caused by `X` being constructible from `variant<Types...>` and
```c++
template<typename T, ...> variant(T&&)
```
being a better match than
```c++
variant(variant<Types...> const& old)
```
when the actual argument is a non-const reference.

Possible solutions:
 - add non-const copy overload `variant(variant<Types...> & old)`
 - add `&& !is_same<Traits::value_type, variant<Types...>>::value` to `enable_if` in the universal constructor template

**Comment by springmeyer** [comment] 2016-10-05 17:12
Thanks for reporting @ukreator and for the thoughts on solutions @lightmare. @artemp is out on vacation this week but I know he's planning a v1.1.x release soon after returning. I've assigned this to 1.1.3 to consider fixing before the next release.

**Comment by artemp** [comment] 2016-10-24 08:56
@lightmare - thanks for digging! Adding an extra check in universal ctor and explicitly disabling passing variants in there is the winner:

```c++
&& !std::is_same<variant<Types...>, typename Traits::value_type>::value
```

**Comment by artemp** [comment] 2016-10-24 08:57
@ukreator - Thanks for reporting and providing test-case !

**Closed** 2016-10-24 09:01 UTC
