### ISSUE TITLE
Problem with std::string and g++ 5.1

### ISSUE THREAD

**Issue by lordnn** [mapbox/variant#40] opened 2015-09-08 17:33 UTC
std::string in g++ 5.1 standard library implements "small string optimization" idiom. And variant with small std::string value can't be swapped with the any other.

**Comment by springmeyer** [comment] 2015-09-08 18:10
@lordnn - are you seeing a compile error with g++ 5.1? If so, can you share the details?

**Comment by lordnn** [comment] 2015-09-08 21:47
There are no compile error and no runtime error but result is wrong. Pseudo code is below.
string s1 ("small string"), s2;
variant v1, v2;
v1.set <string>(s1);
v2=v1;
s2=v2.get <string>(); // s2 has wrong value

**Comment by lordnn** [comment] 2015-09-09 09:55
I think this is exactly the same problem as described in #5 issue.

**Comment by lordnn** [comment] 2015-09-09 14:44
Non pseudo code is:
#include "variant.hpp"
#include <string>
#include <iostream>

template <typename... Types> using variant = mapbox::util::variant<Types...>;

int main(){
  variant<std::string> a;
  a = std::string("ACTIVATION");
  std::cout << a.get<std::string>() << std::endl;
}

**Comment by lordnn** [comment] 2015-09-12 08:04
Same problem on g++ 5.2.

**Comment by hjanetzek** [comment] 2015-10-13 11:58
@lordnn, yes #5 seems to be the issue here. The swap method of the new std::string is not that trivial :)
As a workaround this works for me: 

```
    // conversions
    // move-assign
    template <typename T>
    VARIANT_INLINE variant<Types...>& operator=(T && rhs) noexcept
    {
        helper_type::destroy(type_index, &data);

        constexpr std::size_t index = detail::value_traits<typename std::remove_reference<T>::type, Types...>::index;
        constexpr std::size_t target_index = sizeof...(Types) - index - 1;
        using target_type = typename detail::select_type<target_index, Types...>::type;
        new (&data) target_type(std::forward<T>(rhs));
        type_index = index;
        
        return *this;
    }

    // copy-assign
    template <typename T>
    VARIANT_INLINE variant<Types...>& operator=(T const& rhs)
    {
//        variant<Types...> temp(rhs);
//        helper_type::move(temp.type_index, &temp.data, &data);
//        type_index = temp.type_index;
        
        helper_type::destroy(type_index, &data);

        constexpr std::size_t index = detail::value_traits<typename std::remove_reference<T>::type, Types...>::index;
        constexpr std::size_t target_index = sizeof...(Types) - index - 1;
        using target_type = typename detail::select_type<target_index, Types...>::type;
        new (&data) target_type(rhs);
        type_index = index;
        return *this;
    }
```

**Comment by joto** [comment] 2015-12-04 15:26
I can not reproduce this. I guess this has been fixed as a result of 39a631394e185f527159164c8b0fffae755b8512.
@lordnn can you confirm this?
@artemp: anything to add? can we close this and #5?

**Comment by springmeyer** [comment] 2015-12-04 15:38
@joto yes, this is fixed. So I will close. The followups needed are just coverage to make sure it does not regress:

 - https://github.com/mapbox/variant/issues/42
 - https://github.com/mapbox/variant/issues/39

**Closed by springmeyer** 2015-12-04 15:38 UTC

**Comment by hjanetzek** [comment] 2015-12-04 15:41
@joto, did you build with -D_GLIBCXX_USE_CXX11_ABI=1? It is enabled by default on Ubuntu 15.10 but not on e.g. Arch

**Comment by joto** [comment] 2015-12-04 15:48
@hjanetzek just tried. works with that, too.

**Comment by hjanetzek** [comment] 2015-12-04 15:53
Ah right, direct_swap uses the appropriate swap implementation. Thanks!

**Comment by lordnn** [comment] 2015-12-14 18:27
I wrote my own workaround based on std::is_trivially_copyable. But I think your solution works too.
