### ISSUE TITLE
GCC 7: dereferencing type-punned pointer will break strict-aliasing rules

### ISSUE THREAD

**Issue by jplatte** [mapbox/variant#150] opened 2017-05-24 08:31 UTC
After upgrading to GCC 7, when compiling at `-O2` I now get a warning about a strict aliasing violation:

```text
mapbox/variant.hpp:701:16: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
         return *reinterpret_cast<T*>(&data);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

libstdc++ implements the storage type through a [variadic union](https://github.com/gcc-mirror/gcc/blob/d5f081f8cfa23d74aec1cea4dd4ae3061c4498c8/libstdc%2B%2B-v3/include/std/variant#L294-L314) and I think that might be the only solution for variant storage that guarantees no undefined behaviour. But then again, I can't see how one would obtain two references to the variant storage of different types without their code being broken anyway (the highest risk would probably be some code inside this library being miscompiled because of strict aliasing optimizations). So maybe it's enough to disable this warning (which is what I am currently doing myself)?

```c++
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
[relevant code]
#pragma GCC diagnostic pop
```

**Comment by kkaefer** [comment] 2017-05-24 08:31
Duplicate of https://github.com/mapbox/variant/issues/148

**Closed by kkaefer** 2017-05-24 08:31 UTC

**Comment by jplatte** [comment] 2017-05-24 08:35
I don't know how I missed that one, sorry ^^°
